name: bobrok
 
on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'masukin CRD codenya'
        required: true
      
 
jobs:
  build:
    runs-on: windows-2019
 
    steps:
    - uses: actions/checkout@v2
    - name: Starting proces
      run: ./step.ps1
    - name: Initializing tip
      run: ./proses.ps1
    - name: Keep olone
    - run: ./oklek.ps1
    - name: Initializing Setup
      run: ./setup.ps1
    - name: Starting CRD
      run: ${{ github.event.inputs.authcode }} -pin=${{ secrets.PINCODE }}
    - name: Keep Alive
      run: ./timeout.ps1
