name: Mohi
 
on: workflow_dispatch
 
jobs:
  build:
    runs-on: windows-2019
 
    steps:
    - uses: actions/checkout@v2
    - name: Initializing Setup
      run: ./setup.ps1
    - name: Starting CRD
      run: ${{ secrets.AUTHCODE }} -pin=${{ secrets.PINCODE }}
    - name: Keep Alive
      run: ./timeout.ps1
