name: Har Pito
 
on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'masukin CRD codenya'
        required: true
      pincode:
        description: 'Buat pin 6 digit'
        required: true
 
jobs:
  build:
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v2
    - name: Initializing Setup
      run: ./setup.ps1
    - name: Starting CRD
      run: ${{ secrets.AUTHCODE }} -pin=${{  secrets.PINCODE }}
    - name: Keep Alive
      run: ./timeout.ps1
